name: Comment on Release

on:
  repository_dispatch:
    types: [release]

jobs:
  comment:
    name: Comment on Release
    if: github.repository == 'mcansh/nightly-release-test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install

      - name: Comment on issues
        run: node ./scripts/comment.mjs
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          VERSION: ${{ github.event.client_payload.ref }}
