name: Comment on Release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  comment:
    name: Comment on Release
    if: github.repository == 'mcansh/nightly-release-test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install

      - name: Get Version
        id: version
        run: |
          NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          VERSION=$(npm info @mcansh/nightly-release-test-two version)
          echo ::set-output name=VERSION::${VERSION}

      - name: Comment on issues
        run: node -r esbuild-register scripts/comment.ts
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.version.outputs.VERSION }}
          DEFAULT_BRANCH: "main"
          NIGHTLY_BRANCH: "dev"
