name: 📦 Merged PR

on:
  push:
    branches:
      - dev

jobs:
  if_merged:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "awaiting release"
          number: ${{ github.event.pull_request.number }}
          repo: "mcansh/nigthly-release-test"
