name: Deploy Nightly
on:
  workflow_dispatch:
  schedule:
    # - cron: "0 21 * * *" # every day at 7PM EST
    - cron: "*/20 * * * *" # every 20 minutes

jobs:
  nightly:
    name: Nightly Release
    if: github.repository == 'mcansh/nightly-release-test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NIGHTLY_PAT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        
      - name: Set up git
        run: |
          git config user.email "hello@remix.run"
          git config user.name "Remix Run Bot"
          
      - name: Make a change
        run: |
          NOW=$(date +'%Y-%m-%d')
          echo "console.log(\"greetings ${NOW}\");" > ./src/index.ts
          git add .
          git commit -m "chore: updated ${NOW}"

      - name: Build
        run: npm run build

      - name: Update Version
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          NEXT_VERSION=0.0.0-nightly-${SHORT_SHA}

          git checkout -b nightly/${NEXT_VERSION}
          npm version ${NEXT_VERSION}

          git push origin --tags

      - name: Publish
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
